language: android
dist: trusty

android:
  components:
    - build-tools-28.0.3
    - android-28
    - add-on
    - extra

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-16
    #- sys-img-armeabi-v7a-android-21
    #- sys-img-armeabi-v7a-android-22
    #- sys-img-armeabi-v7a-android-25

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-sdk-preview-license-.+'